### ISSUE TITLE
Fails on WASM

### ISSUE THREAD

**Issue by nokierae** [JonahPlusPlus/bevy_atmosphere#22]
You may already be aware of this, but since WebGL 2.0 isn't standard yet, web builds fail at runtime because there isn't support for compute shaders. I know you just switched over to compute shaders, but is there a way to also support wasm?

Here is the error I get:

```
panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_bind_group_layout
      note: label = `bevy_atmosphere_associated_bind_group_layout`
    too many bindings of type StorageTextures in stage COMPUTE, limit is 0, count was 1
```

**Comment by JonahPlusPlus** [comment]
I decided to prioritize faster native performance over slow browser support. When WebGPU ships, this should fix itself. For now, projects that target browsers shouldn't use this library (I recommend copying the skybox code and importing a pre-rendered sky texture).

**Comment by nokierae** [comment]
I figured as much. Thanks!

**Comment by ericvrp** [comment]
In about how much time will WebGPU be supported in major browsers? It's a pitty I need to disable this crate again.

**Comment by JonahPlusPlus** [comment]
@ericvrp It can be enabled in every major desktop browser via [flags](https://caniuse.com/webgpu) (Firefox is the only mobile browser with support). You can check the roadmap on [Google](https://developer.chrome.com/docs/web-platform/webgpu/#status). Underneath that section, Google says their origin trial is expected to end with Chrome 109 on February 1st, 2023, so we can expect a stable release within a year (maybe? not entirely sure how these things work).

**Comment by ericvrp** [comment]
On mobile it will takes ages unfortunately to have a 90+% chance of users being able to use this. With the current minimal support for mobile builds a working WASM build still be very nice though. Maybe a fallback skybox would be nice. Hopefully this code doesn't need to be ever touched again.

**Comment by JonahPlusPlus** [comment]
I'll consider it down the line. Bevy is still in development and stuff is going to change around, so I would rather wait to see the state of things once it is more stable.
The way I see it: 3D programs are better as apps, where they don't have the overhead of the browser (and don't have to be downloaded every time it's opened). I would rather not add support for mobile browser users who can't/won't get updates (since if they can't get updates, it's likely because they have an older, slower device, and the slower shader will run terribly on it).
However, if it turns out that WebGL 2 compatibility is needed, I can add it in later. I just don't want to maintain something too niche.

**Comment by dsouleyreau** [comment]
Could it be possible to bring back the "old slow code" that worked for the web and enable it with a feature flag like "webgl"?
